Web1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Components.Routing;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Claims;
using Web1.Data;
using Web1.Models;
using Web1.Service;
using Web1.ViewModel;

namespace Web1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext _context;
        public HomeController(ILogger<HomeController> logger, AppDbContext context )
        {
           _context = context;
        }

        public IActionResult Index()
        {
           
            return View();
        }
        [HttpGet]
        public IActionResult LogIn()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login([FromBody] LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = _context.users.FirstOrDefault(u =>
                            u.Email == model.Email && u.Password == model.Password);

                if (user != null)
                {
                    var claims = new List<Claim>
                {
                        new Claim(ClaimTypes.NameIdentifier, user.UerId.ToString()),
                    new Claim(ClaimTypes.Name, user.Email),
                    new Claim(ClaimTypes.Role, user.Role ?? "User")
                };

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                    return Ok();

                }

                ViewBag.Error = "Email hoặc mật khẩu không đúng!";
            }

            return BadRequest();
        }

        [HttpPost]
        public IActionResult SubscribeEmail([FromBody] SubscribeViewModel model)
        {
            if (!ModelState.IsValid)
            {
      
                return BadRequest(new {message=" Email không đúng định dạng"});
            }
            try
            {
                var exist = _context.subscribers.Any(x => x.Email == model.Email);
                if (exist)
                {
                    return BadRequest(new {message= "Email đã được đăng ký trước đó" });
                }
                _context.subscribers.Add(new Subscriber
                {
                    Email = model.Email,
                    TimeSent = DateTime.Now,
                    Status = "enable"
                });
                _context.SaveChanges();
                return Ok(new { message = "Cảm ơn bạn đã đăng ký" });
            }
            catch (Exception)
            {
                return BadRequest(new { message = "Email không hợp lẹ hoặc có lỗi xảy ra" });
                throw;
            }
           
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web1/ViewComponents/ContactViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Web1.Service;

namespace Web1.ViewComponents
{
    public class ContactViewComponent :ViewComponent
    {
        private IContactService _contactService;
        public ContactViewComponent(IContactService contactService)
        {
            _contactService = contactService;
        }
        public IViewComponentResult Invoke()
        {
            var data = _contactService.GetContact();
            return View(data);
        }
    }
}

Web1/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Web1.Service;

namespace Web1.ViewComponents
{
    public class FooterViewComponent :ViewComponent
    {
        private IFooterService _footerService;
        public FooterViewComponent(IFooterService footerService)
        {
            _footerService = footerService;
        }
        public IViewComponentResult Invoke()
        {
            var data = _footerService.GetSampleFooter();
            return View(data);
        }
    }
}

Web1/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Web1.Service;

namespace Web1.ViewComponents
{
    public class HeaderViewComponent: ViewComponent
    {
        private IHeaderService _headervice;
        public HeaderViewComponent(IHeaderService headervice)
        {
            _headervice = headervice;
        }
        public IViewComponentResult Invoke()
        {
            var data = _headervice.GetHeader();
            return View(data);
        }
    }
}

Web1/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Web1.Service;

namespace Web1.ViewComponents
{
    public class MenuViewComponent : ViewComponent 
    {
        private IMenuService _menuService;
        public MenuViewComponent(IMenuService menuService)
        {
            _menuService = menuService;
        }
        public IViewComponentResult Invoke()
        {
            var data = _menuService.GetMenu();
            return View(data);
        }
    }
}

Web1/Views/Home/Index.cshtml
@using Web1.ViewModel
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
    
}

@await Component.InvokeAsync("Menu")

@await Component.InvokeAsync("Header")

@await Component.InvokeAsync("ServiceFeature")

@await Component.InvokeAsync("TestYone")

@await Component.InvokeAsync("Introduce")
@await Component.InvokeAsync("Partners")
@await Component.InvokeAsync("Contact")

@await Component.InvokeAsync("Footer")

Web1/Views/Home/LogIn.cshtml
@{
    ViewData["Title"] = "LogIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .login-box {
        max-width: 400px;
        margin: 80px auto;
        padding: 30px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        border-radius: 10px;
    }
</style>
<div class="login-box">
    <h3 class="text-center mb-4">Đăng nhập quản trị</h3>

    <div class="mb-3">
        <label for="email" class="form-label">Tài khoản</label>
        <input type="text" class="form-control" id="email" required />
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Mật khẩu</label>
        <input type="password" class="form-control" id="password" required />
    </div>

    <button id="loginButton" class="btn btn-danger w-100">Đăng nhập</button>
</div>


<script>
    document.getElementById('loginButton').addEventListener('click', async function (e) {
        e.preventDefault(); // Ngăn reload lại trang

        const email = document.getElementById('email').value;
        const password = document.getElementById('password').value;

        const response = await fetch('/Home/Login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                email,
                password
            })
        });

        if (response.ok) {
            const result = await response.text();
            window.location.href = "/Admin/HomeAdmin/Index";
        } else {
            alert("Đăng nhập thất bại. Vui lòng kiểm tra tài khoản và mật khẩu.");
        }
    });
</script>